# Generated by Django 5.2.3 on 2025-07-09 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("evaluation_system", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedbackReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_file", models.FileField(upload_to="feedback_reports/")),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "evaluation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="evaluation_system.overallinterviewevaluation",
                    ),
                ),
            ],
        ),
    ]
