# Generated by Django 5.2.3 on 2025-06-22 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("interview_scenarios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResponseMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("audio_duration", models.DurationField(blank=True, null=True)),
                ("video_duration", models.DurationField(blank=True, null=True)),
                ("upload_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="response_metadata",
                        to="interview_scenarios.interviewquestion",
                    ),
                ),
            ],
        ),
    ]
