# Generated by Django 5.2.3 on 2025-06-21 18:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_emailverificationcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailverificationcode",
            name="expires_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
