# Generated by Django 5.2.3 on 2025-06-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_emailverificationcode_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_email_verified",
            field=models.BooleanField(default=True),
        ),
    ]
