# Generated by Django 5.2.3 on 2025-07-06 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("client_media_manager", "0001_initial"),
        ("interview_manager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="responsemetadata",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="response_metadata",
                to="interview_manager.interviewquestion",
            ),
        ),
    ]
