# Generated by Django 5.2.3 on 2025-07-10 15:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_manager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "男"), ("F", "女"), ("O", "其他")],
                default="O",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="major",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                default="",
                max_length=11,
                validators=[
                    django.core.validators.RegexValidator(
                        message="手机号格式错误，应为11位数字", regex="^1[3-9]\\d{9}$"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="university",
            field=models.CharField(blank=True, default="汉", max_length=100),
        ),
    ]
