# Generated by Django 5.2.3 on 2025-07-19 12:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_manager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="age",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message="年龄不能小于1"
                    ),
                    django.core.validators.MaxValueValidator(
                        120, message="年龄不能大于120"
                    ),
                ],
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="learning_stage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FRESHMAN_1", "大一上"),
                    ("FRESHMAN_2", "大一下"),
                    ("SOPHOMORE_1", "大二上"),
                    ("SOPHOMORE_2", "大二下"),
                    ("JUNIOR_1", "大三上"),
                    ("JUNIOR_2", "大三下"),
                    ("SENIOR_1", "大四上"),
                    ("SENIOR_2", "大四下"),
                    ("GRADUATE_STUDENT", "研究生"),
                    ("JOB_SEEKER", "应届生"),
                    ("EMPLOYED", "社会人士"),
                    ("OTHER", "其他"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
