# Generated by Django 5.2.3 on 2025-07-10 16:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_manager", "0002_user_name_alter_user_gender_alter_user_major_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                default="",
                max_length=11,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="手机号格式错误，应为11位数字", regex="^1[3-9]\\d{9}$"
                    )
                ],
            ),
        ),
    ]
