# Generated by Django 5.2.3 on 2025-07-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interview_manager", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interviewscenario",
            name="is_real_time",
            field=models.BooleanField(default=True),
        ),
    ]
